FROM ubuntu:18.04
RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN apt-get clean
RUN apt-get update
RUN apt-get install -y libssl-dev
RUN apt-get install -y libgssapi-krb5-2
RUN apt-get install -y ca-certificates
RUN apt-get install git git-lfs curl perl
COPY . /
RUN chmod -R +x /fastgithub_linux-x64
ADD posix/* /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/clone"]